import type { PublicMenuCategory, PublicMenuProduct, PublicRestaurant } from "./types";

export const publicRestaurant: PublicRestaurant = {
  name: "Le Bistrot des Halles",
  slug: "le-bistrot-des-halles",
  serviceStatus: "open",
  paymentNote: "Paiement à la caisse ou auprès du serveur.",
};

export const publicMenuCategories: PublicMenuCategory[] = ["Entrées", "Plats", "Desserts", "Boissons"];

export const publicMenuProducts: PublicMenuProduct[] = [
  {
    id: "salade-cesar",
    category: "Entrées",
    name: "Salade César",
    price: 13.5,
    description: "Poulet grillé, parmesan, croûtons, sauce césar",
    allergens: ["Œuf", "Lait"],
    available: true,
    promo: false,
  },
  {
    id: "burrata-tomate",
    category: "Entrées",
    name: "Burrata tomate",
    price: 11,
    description: "Burrata crémeuse, tomates, basilic, huile d’olive",
    allergens: ["Lait"],
    available: true,
    promo: false,
  },
  {
    id: "burger-classique",
    category: "Plats",
    name: "Burger Classique",
    price: 18,
    description: "Steak haché, cheddar, salade, tomate, oignons rouges, sauce maison",
    allergens: ["Gluten", "Lait", "Sésame"],
    available: true,
    promo: true,
    promoLabel: "-10 %",
  },
  {
    id: "frites-maison",
    category: "Plats",
    name: "Frites Maison",
    price: 4.5,
    description: "Frites fraîches préparées sur place",
    allergens: ["Vegan"],
    available: true,
    promo: false,
  },
  {
    id: "risotto-du-marche",
    category: "Plats",
    name: "Risotto du marché",
    price: 17,
    description: "Riz crémeux, légumes de saison, parmesan",
    allergens: ["Lait"],
    available: false,
    promo: false,
  },
  {
    id: "tiramisu",
    category: "Desserts",
    name: "Tiramisu",
    price: 6.5,
    description: "Mascarpone, café, biscuits cacao",
    allergens: ["Gluten", "Lait", "Œuf"],
    available: true,
    promo: true,
    promoLabel: "-10 %",
  },
  {
    id: "cafe-gourmand",
    category: "Desserts",
    name: "Café gourmand",
    price: 7.5,
    description: "Café accompagné de mini desserts",
    allergens: ["Gluten", "Lait"],
    available: true,
    promo: false,
  },
  {
    id: "limonade",
    category: "Boissons",
    name: "Limonade",
    price: 3.5,
    description: "Citron, menthe fraîche",
    allergens: ["Sans"],
    available: true,
    promo: false,
  },
  {
    id: "eau-petillante",
    category: "Boissons",
    name: "Eau pétillante",
    price: 2.8,
    description: "Bouteille 50cl",
    allergens: ["Sans"],
    available: true,
    promo: false,
  },
];
